#!/bin/bash

. config.inc.sh

bin=./audio-ai-telegram-bot
if [ ! -x "$bin" ]; then
	bin="go run *.go"
fi

BOT_TOKEN=$BOT_TOKEN \
ALLOWED_USERIDS=$ALLOWED_USERIDS \
ADMIN_USERIDS=$ADMIN_USERIDS \
ALLOWED_GROUPIDS=$ALLOWED_GROUPIDS \
TTS_BIN=$TTS_BIN \
TTS_DEFAULT_MODEL=$TTS_DEFAULT_MODEL \
STT_BIN=$STT_BIN \
MDX_BIN=$MDX_BIN \
RVC_BIN=$RVC_BIN \
RVC_MODEL_PATH=$RVC_MODEL_PATH \
RVC_DEFAULT_MODEL=$RVC_DEFAULT_MODEL \
RVC_TRAIN_BIN=$RVC_TRAIN_BIN \
RVC_TRAIN_DEFAULT_BATCH_SIZE=$RVC_TRAIN_DEFAULT_BATCH_SIZE \
RVC_TRAIN_DEFAULT_EPOCHS=$RVC_TRAIN_DEFAULT_EPOCHS \
MUSICGEN_BIN=$MUSICGEN_BIN \
AUDIOGEN_BIN=$AUDIOGEN_BIN \
$bin $*
